# Generated by Django 4.1.3 on 2023-01-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
