# Generated by Django 4.1.3 on 2023-01-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_rename_gender_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
