# Generated by Django 4.1.3 on 2023-01-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
