# Generated by Django 4.1.3 on 2023-01-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
