# Generated by Django 4.1.3 on 2023-01-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
