# Generated by Django 4.1.3 on 2023-01-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_delete_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
