# Generated by Django 4.1.3 on 2023-01-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
